/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void test1() {
        assertEquals(1,1);
    }
}
