/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for Feature #5: View List of Recipes
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class DetailedRecipeDisplayTest {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    /* --------------------------------- BDD TESTS --------------------------------- */
}
