/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for Feature #3: Detailed Recipe Display
 */
package cse.gradle;

import org.junit.jupiter.api.Test;

import cse.gradle.View.RecipeList;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;


class Feature3Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test
    void recipeDetailsAvailable() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe r = mock.generateNewRecipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");
        assertEquals("breakfast", r.getCategory());
        assertEquals("eggs, bacon", r.getIngredients());
        assertEquals("cook for 10 minutes", r.getInstructions());
        assertEquals("American breakfast", r.getName());
    }
    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test
    void viewRecipeDetailsInListView() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe r1 = mock.generateNewRecipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");
        Recipe r2 = mock.generateNewRecipe("lunch", "salmon, salad", "cook for 20 minutes", "Healthy Lunch");        
        List<Recipe> list = new ArrayList<Recipe>();
        list.add(r1);
        list.add(r2);
        MockView view = new MockView(list);
        assertEquals("breakfast", r1.getCategory());
        assertEquals("eggs, bacon", r1.getIngredients());
        assertEquals("cook for 10 minutes", r1.getInstructions());
        assertEquals("American breakfast", r1.getName());
        assertEquals("lunch", r2.getCategory());
        assertEquals("salmon, salad", r2.getIngredients());
        assertEquals("cook for 20 minutes", r2.getInstructions());
        assertEquals("Healthy Lunch", r2.getName());
    }
}
