/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for Feature #9: User Account Creation
 */
package cse.gradle;

import org.bson.Document;
import org.junit.jupiter.api.Test;

import cse.gradle.Server.MongoDB;
import cse.gradle.Server.Server;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;


class Feature13Tests extends HTTPServerTests{
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test 
    void checkServerError() {
        Server.stopServer();

        // Check for login error
        Model model = new MockModel();
        String response = model.performLoginRequest("test_user", "password");
        String error = "Error: Server down";
        assertEquals(error, response);

        // Check for generic request error
        Recipe originalRecipe = new Recipe("potatoes", "boil the potatoes", "brunch", "boiled potatoes");
        response = model.postRecipe(originalRecipe);
        error = "Error: Server down";
        assertEquals(error, response);
    }
}
