/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for Feature #7: Recipe Deletion
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;


class Feature7Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test 
    void deleteExistingRecipe() {
        Recipe r = new Recipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");        
        List<Recipe> list = new ArrayList<Recipe>();
        list.add(r);
        RecipeList rl = new RecipeList(list);
        rl.getRecipes().remove(0);
        assertEquals(true, rl.getRecipes().isEmpty());
    }
    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test
    void generateRecipeAndDelete() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe r = mock.generateNewRecipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");
        List<Recipe> list = new ArrayList<Recipe>();
        list.add(r);
        RecipeList rl = new RecipeList(list);
        rl.getRecipes().remove(0);
        assertEquals(true, rl.getRecipes().isEmpty());
    }   
}
