/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for Feature #6: Recipe Editing
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class Feature6Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test 
    void editCategory() {
        Recipe r = new Recipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");
        r.setName("European lunch");
        assertEquals("European lunch", r.getName());
    }
    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test
    void generateAndEditEntireRecipe() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe r = mock.generateNewRecipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");
        r.setCategory("lunch");
        r.setName("European lunch");
        r.setIngredients("flour");
        r.setInstructions("cook 30 minutes");
        assertEquals("lunch", r.getCategory());
        assertEquals("European lunch", r.getName());
        assertEquals("flour", r.getIngredients());
        assertEquals("cook 30 minutes", r.getInstructions());
    }   
}
