/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for Feature #4: Recipe Saving
 */
package cse.gradle;

import org.junit.jupiter.api.Test;

import cse.gradle.*;
import cse.gradle.View.RecipeList;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;


class Feature4Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test
    void saveRecipeCategory() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe r = mock.generateNewRecipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");
        r.setCategory("lunch");
        r.setName("European lunch");
        assertEquals("lunch", r.getCategory());
        assertEquals("European lunch", r.getName());
    }
    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test
    void saveNewRecipe() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe r2 = mock.generateNewRecipe("lunch", "salmon, salad", "cook for 20 minutes", "Healthy Lunch");        
        List<Recipe> list = new ArrayList<Recipe>();
        list.add(r2);
        MockView view = new MockView(list);;
        Recipe recipe = view.getRecipeList().get(0);
        assertEquals("lunch", recipe.getCategory());
        assertEquals("salmon, salad", recipe.getIngredients());
        assertEquals("cook for 20 minutes", recipe.getInstructions());
        assertEquals("Healthy Lunch", recipe.getName());
    }
}
