/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for User Story #9: User Account Creation
 */
package cse.gradle;

import org.bson.Document;
import org.junit.jupiter.api.Test;

import cse.gradle.Server.MongoDB;
import cse.gradle.Server.Server;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;


class Feature13Tests extends HTTPServerTests{
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test 
    void checkLoginError() {
        Server.stopServer();

        Model model = new MockModel();
        String response = model.performLoginRequest("test_user", "password");
        String error = "Error: Server down";
        assertEquals(error, response);
    }

    @Test 
    void checkRecipeError() {
        Server.stopServer();

        Model model = new MockModel();
        Recipe originalRecipe = new Recipe("potatoes", "boil the potatoes", "brunch", "boiled potatoes");
        String response = model.postRecipe(originalRecipe);
        String error = "Error: Server down";
        assertEquals(error, response);
    }

    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test 
    void completeServerErrorTest() {
        // login with test user
        Model model = new MockModel();
        String retrievedUserId = model.performLoginRequest("test_user", "password");
        assertEquals(MockModel.mockUserId, retrievedUserId);

        // cut connection and ask for recipe
        Server.stopServer();
        Recipe originalRecipe = new Recipe("potatoes", "boil the potatoes", "brunch", "boiled potatoes");
        String response = model.postRecipe(originalRecipe);
        String error = "Error: Server down";
        assertEquals(error, response);
    }
}
