/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for User Story #18: Share Recipe by Unique URL 
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;


class Feature18Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    
    
    /* --------------------------------- BDD TESTS --------------------------------- */
}
