/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for User Story #_: ___________
 */
package cse.gradle;

import org.junit.jupiter.api.Test;

import cse.gradle.Server.Server;

import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;


class Feature18Tests {
    @Test 
    void checkShare() {
        MockModel model = new MockModel();
        MockView view = new MockView(new ArrayList<Recipe>());
        MockController controller = new MockController();
        Recipe recipe = new Recipe("eggs, bacon", "cook for 10 minutes", "breakfast", "American breakfast");
        
        assertEquals("html", controller.shareRecipe(recipe));
    }
}
