/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for User Story #19: View Recipe on Webpage
 */
package cse.gradle;

import org.junit.jupiter.api.Test;

import javafx.scene.input.Clipboard;
import javafx.scene.input.ClipboardContent;

import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.List;


class Feature19Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test
    void webPageCreated() {
        Model mockModel = new MockModel();
        String recipeID = "e4301da9-cb31-43a2-8172-5d80abdd31bd";
        String shareLink = mockModel.getShareLink(recipeID);

        assert(shareLink.toString() != null);
    }
    
    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test 
    void userLoginAndWebpageCreated() {
        User Joe = new User("abc", "abc");
        Recipe r1 = new Recipe("eggs, bacon", "cook for 10 minutes", "breakfast", "American breakfast");
        Recipe r2 = new Recipe("salmon, salad", "cook for 20 minutes", "breakfast", "Healthy Lunch");
        Recipe r3 = new Recipe("potatoes", "boil the potatoes", "dinner", "boiled potatoes");
        Recipe r4 = new Recipe("salmon", "boil the salmon", "dinner", "boiled salmon");
        List<Recipe> rList = new ArrayList<>();
        rList.add(r1);
        rList.add(r2);
        rList.add(r3);
        rList.add(r4);
        Joe.setRecipeList(null);
        Model mockModel = new MockModel();
        String recipeID = "e4301da9-cb31-43a2-8172-5d80abdd31bd";
        String shareLink = mockModel.getShareLink(recipeID);

        assert(shareLink.toString() != null);
    }
}
