/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for Feature #1: Meal Type Selection
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;


class Feature2Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test
    void specifyMealType() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe r = mock.generateNewRecipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");
        assertEquals("breakfast", r.getCategory());
    }
    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test
    void selectMealType() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe r = mock.generateNewRecipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");
        List<Recipe> list = new ArrayList<Recipe>();
        list.add(r);
        MockView view = new MockView(list);;
        assertEquals("breakfast", view.getRecipeList().get(0).getCategory());
    }
}
