/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for Feature #1: Recipe Creation
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;


class Feature1Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test
    void recipeInitialization() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe r = mock.generateNewRecipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");
        assertEquals("breakfast", r.getCategory());
        assertEquals("eggs, bacon", r.getIngredients());
        assertEquals("cook for 10 minutes", r.getInstructions());
        assertEquals("American breakfast", r.getName());
    }
    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test
    void recipeCreation() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe r = mock.generateNewRecipe("breakfast", "eggs, bacon", "cook for 10 minutes", "American breakfast");
        List<Recipe> list = new ArrayList<Recipe>();
        list.add(r);
        MockView view = new MockView(list);
        assertEquals(list, view.getRecipeList());
    }
}
