/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for Feature #5: View List of Recipes
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;


class Feature5Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test 
    void viewRecipeName() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe recipe = mock.generateNewRecipe("1","2","3","4");
        Recipe recipe2 = mock.generateNewRecipe("potatoes", "boil the potatoes", "brunch", "boiled potatoes");
        assertEquals("4", recipe.getName());
        assertEquals("boiled potatoes", recipe2.getName());
    }
    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test
    void viewMultipleRecipes() {
        MockRecipeGenerator mock = new MockRecipeGenerator();
        Recipe recipe = mock.generateNewRecipe("1","2","3","4");
        Recipe recipe2 = mock.generateNewRecipe("potatoes", "boil the potatoes", "brunch", "boiled potatoes");
        List<Recipe> list = new ArrayList<Recipe>();
        list.add(recipe);
        list.add(recipe2);
        RecipeList rl = new RecipeList(list);
        Recipe listRecipe = rl.getRecipes().get(0);
        Recipe listRecipe2 = rl.getRecipes().get(1);
        assertEquals("4", listRecipe.getName());
        assertEquals("boiled potatoes", recipe2.getName());
    }
}
