/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for User Story #_: ___________
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;


class Feature21Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test
    void autoLogin() {
        MockController controller = new MockController();
        boolean loginStatus = false;
        try {
             loginStatus = controller.loginUser("abc", "abc");
        } catch (Exception e) {
            System.out.println(e);
        }
        assert(!loginStatus);
    }
    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test 
    void loginLogout() {
        User Joe = new User("abc", "abc");
        MockController controller = new MockController();
        boolean loginStatus = false;
        try {
             loginStatus = controller.loginUser(Joe.getUsername(), Joe.getPassword());
        } catch (Exception e) {
            System.out.println(e);
        }
        assert(!loginStatus);
        Joe = new User("login", "checked");
        loginStatus = true;
        try {
             loginStatus = controller.loginUser(Joe.getUsername(), Joe.getPassword());
        } catch (Exception e) {
            System.out.println(e);
        }
        assert(loginStatus);
    }
}
