/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for User Story #14: Meal Type Tags
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.List;


class Feature14Tests {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test
    void addMealTypeTag() {
        Recipe r1 = new Recipe("eggs, bacon", "cook for 10 minutes", "breakfast", "American breakfast");
        Recipe r2 = new Recipe("salmon, salad", "cook for 20 minutes", "lunch", "Healthy Lunch");
        Recipe r3 = new Recipe("potatoes", "boil the potatoes", "dinner", "boiled potatoes");
        List<Recipe> rList = new ArrayList<>();
        
        rList.add(r1);
        rList.add(r2);
        rList.add(r3);
        
        assertEquals(r1.getCategory(), "breakfast");
        assertEquals(r2.getCategory(), "lunch");
        assertEquals(r3.getCategory(), "dinner");
    }
    
    /* --------------------------------- BDD TESTS --------------------------------- */
    @Test
    void manipulatingTypeTagsInView() {
        Recipe r1 = new Recipe("eggs, bacon", "cook for 10 minutes", "breakfast", "American breakfast");
        Recipe r2 = new Recipe("salmon, salad", "cook for 20 minutes", "lunch", "Healthy Lunch");
        Recipe r3 = new Recipe("potatoes", "boil the potatoes", "dinner", "boiled potatoes");
        List<Recipe> rList = new ArrayList<>();
        rList.add(r1);
        rList.add(r2);
        rList.add(r3);
        
        MockView view = new MockView(rList);
        List<Recipe> rList1 = view.getListOfRecipes();
        
        assertEquals(rList1.get(0).getCategory(), "breakfast");
        assertEquals(rList1.get(1).getCategory(), "lunch");
        assertEquals(rList1.get(2).getCategory(), "dinner");
    }
}
