/*
 * This Java source file was generated by the Gradle 'init' task.
 * 
 * 
 * Functionality: Includes Unit and BDD Scenario Testing for Feature #5: View List of Recipes
 */
package cse.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class ViewListOfRecipiesTest {
    /* --------------------------------- UNIT TESTS --------------------------------- */
    @Test void getRecipeName() {
        Recipe recipe = new Recipe("1","2","3","4");
        Recipe recipe2 = new Recipe("potatoes", "boil the potatoes", "brunch", "boiled potatoes");
        
        assertEquals("4", recipe.getName());
        assertEquals("boiled potatoes", recipe2.getName());
    }
    /* --------------------------------- BDD TESTS --------------------------------- */

}
