name: Unit Tests
run-name: Running Unit Tests for All Tasks

# Controls when the workflow will run
on:
  # Triggers the workflow on push (all branches) or pull requests (main)
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "dummyTest"
  dummyTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs tests within the appropriate test file
      - run: javac -cp lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:. app/src/test/DummyTest.java
      - run: java -cp lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:. org.junit.runner.JUnitCore app/src/test.DummyTest
        
